
public class Logger {

    private static Logger instance;

    private Logger(){

    }

    public static Logger getInstance(){

        if(instance == null){
            instance = new  Logger();
        }

        return instance;
    }

     public void log(String message) {
        System.out.println("LOG: " + message);
    }
}

/*
 * Logger Class Explanation:
 *
 * 1. The Logger class follows the Singleton Design Pattern.
 *
 * 2. The variable 'instance' is declared as static so that only one
 *    object of Logger exists for the entire application.
 *
 * 3. The constructor is declared private to prevent other classes
 *    from creating Logger objects using the 'new' keyword.
 *
 * 4. The getInstance() method provides a global access point to the
 *    single Logger object.
 *
 * 5. When getInstance() is called for the first time, it checks whether
 *    the instance is null. If it is null, a new Logger object is created.
 *
 * 6. On subsequent calls, the already created Logger object is returned,
 *    ensuring that only one instance exists throughout the application.
 *
 * 7. The log() method is used to display log messages generated by
 *    different parts of the application.
 *
 * 8. This implementation helps maintain consistent logging and reduces
 *    unnecessary object creation.
 */